# -*- coding: utf-8 -*-
"""LOSstdList

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCMbC7hwmY00X5WS6ospko6IXHLV_-Fp
"""

import pandas as pd

df_demo = pd.read_csv("/content/PhysicalandAdmission.csv")
los_col = 'LOS'  # Replace if different
std_los = df_demo[los_col].std()
print("std",std_los)
mean = df_demo[los_col].mean()
print("mean",mean)
print(mean + (2*std_los))
print("2 std above mean", mean + (2*std_los))
df_demo = df_demo[df_demo[los_col] >= (mean + (2*std_los))]
print("unqiue",str(len(df_demo["subject_id"].unique())))
print("max_day:",max(df_demo[los_col]))
df_demo.to_csv("PatientLongLos.csv", index=False)
print(df_demo)